# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: medical.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    6,
    '',
    'medical.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmedical.proto\x12\x07medical\"G\n\x0b\x44\x61taRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x14\n\x0cround_number\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\"7\n\x0c\x44\x61taResponse\x12\x16\n\x0eserver_message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32K\n\x10MedCommunication\x12\x37\n\x08SendData\x12\x14.medical.DataRequest\x1a\x15.medical.DataResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'medical_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAREQUEST']._serialized_start=26
  _globals['_DATAREQUEST']._serialized_end=97
  _globals['_DATARESPONSE']._serialized_start=99
  _globals['_DATARESPONSE']._serialized_end=154
  _globals['_MEDCOMMUNICATION']._serialized_start=156
  _globals['_MEDCOMMUNICATION']._serialized_end=231
# @@protoc_insertion_point(module_scope)
